### ISSUE TITLE
Add a test for server start 

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#687] opened 2023-11-24 16:15 UTC
Write a test that does the following

- Starts a GraphQL server on port 8000.
- Make 100 requests to the server.
- Assert the shape of the response received.
- Kill the server and end the test.

**Technical Requirements**
- Use the following GraphQL Config
  ```graphql
  schema @server(port: 8000) {
    query: Query
  }
  
  type Query {
    greet: String @const(data: "Hello World!")
  }
  ```
- Test should run under 100ms.

**Comment by neo773** [comment] 2023-11-24 16:16
Can I get assigned

**Comment by ologbonowiwi** [comment] 2023-11-25 00:18
Hey @yuvrajjsingh0, the issue is already assigned to neo so even if you open a PR before him your PR can be closed as he started to work on it already. 

I highly recommend for you to search any other open issue that does not have anyone assigned to. We have some of them :smiley:

**Comment by melsonic** [comment] 2023-11-26 05:41
I want to work on this one. Can anyone assign this to me?

**Closed** 2023-12-06 11:42 UTC
Labels: maintenance, 💎 Bounty
