### ISSUE TITLE
`tc check` does not fail on missing type

### ISSUE THREAD

**Issue by sujeetsr** [tailcallhq/tailcall#323] opened 2023-09-20 17:15 UTC
Running `check` on the following file with a missing `User` type says "No errors found".  (because it does not try to generate the schema if not passed the `-s` option)

```graphql
schema
  @server(
    port: 8000
    baseURL: "http://jsonplaceholder.typicode.com"
    enableHttpCache: true
    enableGraphiql: "/graphiql"
    enableQueryValidation: false
  ) {
  query: Query
}

type Query {
  posts: [Post] @http(path: "/posts")
}

type Post {
  id: Int!
  userId: Int!
  title: String!
  body: String!
  user: User @http(path: "/users/{{value.userId}}")
}
```

**Comment by tusharmath** [comment] 2023-09-27 07:41
duplicate of #334

**Closed by tusharmath** 2023-09-27 07:41 UTC
Labels: bug, good first issue
