### ISSUE TITLE
GraphQL resolver with invalid arg does not throw error

### ISSUE THREAD

**Issue by ologbonowiwi** [tailcallhq/tailcall#944] opened 2024-01-14 18:20 UTC
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug

I've changed the file [tests/graphql/errors/test-graphqlsource-no-base-url.graphql](https://github.com/tailcallhq/tailcall/blob/main/tests/graphql/errors/test-graphqlsource-no-base-url.graphql) adding a test with an arg declared on `args` but the arg actually does not exist.

### Steps to reproduce

1. add a line below https://github.com/tailcallhq/tailcall/blob/f2623171823b550f2ef2c8a1c2815e3ae89bbc80/tests/graphql/errors/test-graphqlsource-no-base-url.graphql#L12 with the following content: `user: User @graphQL(baseURL: "http://jsonplacheholder.typicode.com", name: "user", args: [{key: "id", value: "{{args.userId}}"}])`
2. run `cargo test`

### Expected behavior

The test should throw, as we don't validate a failure that this argument does not exist.

### Actual behavior
The tests pass normally, because we don't have this validation on graphql operator. This validation exists for `@http` operator. e.g., 
https://github.com/tailcallhq/tailcall/blob/f2623171823b550f2ef2c8a1c2815e3ae89bbc80/tests/graphql/errors/test-field-already-implemented-from-Interface.graphql#L15-L21

### Additional context

Any args passed to the `args` object on `@graphQL` operator should be valid to avoid unexpected behavior at runtime.

**Comment by meskill** [comment] 2024-01-14 21:15
kind of dupe of https://github.com/tailcallhq/tailcall/issues/449. I think we need some general validation for the templates and not just operator specific thing

**Comment by ologbonowiwi** [comment] 2024-01-14 22:30
by any chance we could reuse the validation that we have on `@http`? literally extract the method and use it on the other operators

**Closed** 2024-01-16 16:12 UTC
